# This is an example for a workflow file.
# Place this file in .github/workflows/glua_linter.yml

on: [push, pull_request]

jobs:
  lua_lint:
    runs-on: ubuntu-latest # The action only works on Ubuntu.
    name: GLua Linter # Name this whatever you want.
    steps:
      - name: Checkout # This step is required to clone the repository.
        id: checkout
        uses: actions/checkout@v2
      - name: Linting
        id: action-glua-lint
        # You can change v1.1.1 to a newer version or 'master.' Changing it to 'master' may cause unexpected behavior.
        uses: TASSIA710/action-glua-lint@v1.1.1
        with:
          directory: / # This is the directory to scan. If '/' is selected, it will scan the entire repository.
